name: Integration

on:
    push:
        branches:
            - main

env:
    SOLUTION_DIR: ./InterfaceAnalyzer

jobs:
    test_and_artifact:
        name: Test Project and Upload Artifact
        uses: ./.github/workflows/test-and-artifact-job.yml
        with:
            build-path: $SOLUTION_DIR    

    publish:
        name: Publish as NuGet Package
        needs: test_and_artifact
        uses: ./.github/workflows/publish-job.yml
        with:
            build-path: $SOLUTION_DIR
        

