name: Pack and Publish

on:
  workflow_call:
    inputs:
      build-path:
        description: "Path to the .csproj or .nuspec file to pack"
        required: true
        type: string
      artifact-name:
        description: "Name of the artifact to download"
        required: true
        type: string
      artifact-path:
        description: "Path to download the artifact to"
        required: true
        type: string
      nuget-feed-url:
        description: "Location of the NuGet feed. Only supports GitHub."
        required: true
        type: string
      nuget-feed-owner:
        description: "Owner of the NuGet feed."
        required: true
        type: string

jobs:
  package-and-publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.build-path }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: '9.0.x'
        cache: true

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}

    - name: Add NuGet source
      run: |
        dotnet nuget add source ${{ inputs.nuget-feed-url }} \
        --name github \
        --username ${{ inputs.nuget-feed-owner }} \
        --password ${{ secrets.GITHUB_TOKEN }} \
        --store-password-in-clear-text

    - name: Restore project
      run: dotnet restore

    - name: Package project
      run: >
        dotnet pack
        -c Release 
        --no-build 
        -o ${{ github.workspace }}/artifacts

    - name: Publish package
      run: >
        dotnet nuget push ${{ github.workspace }}/artifacts/*.nupkg
        --source "github"
        --api-key ${{ secrets.GITHUB_TOKEN }}
        --skip-duplicate