name: Quality Checks

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubnutu-latest
        steps:
            # - uses: actions/checkout@v4.2.2
            # - uses: actions/setup-dotnet@v4.3.1
            #   with:
                # dotnet-version: '9'
            - run: echo "This was triggered by a push to ${{ github.ref }}"