name: Quality Checks

on:
    push:
        branches: [ $default-branch ]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            SOLUTION_DIR: ./InterfaceAnalyzer
        defaults:
            run:
                working-directory: ${{ env.SOLUTION_DIR }}
        steps:
            - uses: actions/checkout@v4.2.2
            - uses: actions/setup-dotnet@v4.3.1
              with:
                dotnet-version: '9'
            - run: dotnet restore
            - run: dotnet build --no-restore
            - run: dotnet test --no-build